spring.application.name=chat
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=chat
spring.datasource.password=chadbpassword123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true